name: Terraform CI/CD

on:
  push:
    branches:
      - main
 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
    
permissions:
  contents: read
  issues: write

jobs:
  terraform:
    name: Deploy EKS Cluster
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: 'write'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ vars.AWS_REGION }}

    - name: Terraform Init
      # working-directory: terraform/
      run: terraform init

    - name: Terraform Plan
      # working-directory: terraform/
      run: terraform plan -out=tfplan
    
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_KEY }}
    
    - name: Manual Approval
      if: always()
      uses: trstringer/manual-approval@v1
      timeout-minutes: 5
      with:
        secret: ${{ steps.generate_token.outputs.token }}
        approvers: sheezanrasool
        minimum-approvals: 1
        issue-title: "Deploying"
        issue-body: "Review the terraform plan, then approve or deny the deployment."
        exclude-workflow-initiator-as-approver: false

    - name: Terraform Apply
      if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'approval'

      # working-directory: terraform/
      run: terraform apply tfplan
      env:
        TF_IN_AUTOMATION: "true"

    - name: Deploy to Production
      if: always()
      run: echo "Deploying to Production"

    - name: Notify Slack
      if: always()
      run: echo "Deployment Complete! Notify Slack or other notification mechanism."
