name: Terraform CI/CD

on:
  push:
    branches:
      - main
 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
    
permissions:
  contents: read
  issues: write

jobs:
  terraform:
    name: Deploy EKS Cluster
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region your-aws-region

    - name: Terraform Init
      # working-directory: terraform/
      run: terraform init

    - name: Terraform Plan
      # working-directory: terraform/
      run: terraform plan -out=tfplan
    
    - name: Manual Approval
      if: always()
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: Sheezan
        minimum-approvals: 1
        issue-title: "Deploying"
        issue-body: "Review the terraform plan, then approve or deny the deployment."
        exclude-workflow-initiator-as-approver: false

    - name: Terraform Apply
      if: always()
      # working-directory: terraform/
      run: terraform apply tfplan
      env:
        TF_IN_AUTOMATION: "true"

    - name: Deploy to Production
      if: always()
      run: echo "Deploying to Production"

    - name: Notify Slack
      if: always()
      run: echo "Deployment Complete! Notify Slack or other notification mechanism."
