name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup AWS Credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region your-aws-region

    - name: Terraform Init
      working-directory: terraform/
      run: terraform init

    - name: Terraform Plan
      working-directory: terraform/
      run: terraform plan -out=tfplan

    - name: Create GitHub Release
      id: create_release
      run: echo "Creating Release"
    
    - name: Manual Approval
      if: always()
      uses: JasonEtco/manual-approval@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        custom-id: my-approval-id
        custom-msg: "Do you want to deploy this change?"

    - name: Terraform Apply
      if: always()
      working-directory: terraform/
      run: terraform apply tfplan
      env:
        TF_IN_AUTOMATION: "true"

    - name: Deploy to Production
      if: always()
      run: echo "Deploying to Production"

    - name: Notify Slack
      if: always()
      run: echo "Deployment Complete! Notify Slack or other notification mechanism."
